runtime: nodejs20

instance_class: F2  # Optional: choose F1, F2, F4 depending on need
env: standard       # Use "standard" for basic Node.js apps, or "flex" for custom environments

handlers:
  - url: /.*
    script: auto
