services:
  - type: web
    name: prepmind
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOGETHER_API_KEY
        sync: false # This will need to be set manually in Render dashboard
    autoDeploy: true
